using LibrarySystem.Service;
using Microsoft.OpenApi.Models;

namespace LibrarySystem
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            

            // Add services to the container.

            builder.Services.AddControllers();
            builder.Services.AddScoped<ILibraryService, LibraryService>();
            builder.Services.AddSwaggerGen(c =>
            c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" }));

            var app = builder.Build();

            // Configure the HTTP request pipeline.

            app.UseHttpsRedirection();

            app.UseAuthorization();

            //UseSwagger is a middleware responsible for generating and exposing the Swagger JSON document,
            //which describes my API. This JSON document includes information
            //about mine API's endpoints, parameters, data types, and more.
            //The Swagger JSON document is generated based on the code and metadata (e.g., attributes) in the API project.
            app.UseSwagger();

            //UseSwaggerUI is a middleware that provides a user interface for testing the API
            //This UI reads the Swagger JSON document generated by the UseSwagger middleware
            //and presents it in a visually appealing and easy - to - use way.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API v1");
            });

            app.MapControllers();

            app.Run();
        }
    }
}